version: '2'
services:
    expenses-app:
        image: expenses
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://expenses-postgresql:5432/expenses
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    expenses-postgresql:
        extends:
            file: postgresql.yml
            service: expenses-postgresql
